default:
	gcc Logic.c main.c Node_storage_data.c parse_csv_json_own_edit.c parse_json_local_storage.c write_json_for_web.c parse_malop_for_dang_ki.c -o myprogram
	x86_64-w64-mingw32-gcc Logic.c main.c Node_storage_data.c parse_csv_json_own_edit.c parse_json_local_storage.c write_json_for_web.c parse_malop_for_dang_ki.c -o myprogram.exe